// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  }
});

// Add error handling for auth issues
supabase.auth.onAuthStateChange(async (event, session) => {
  if (event === 'TOKEN_REFRESHED') {
    console.log('🔄 Auth token refreshed successfully');
  } else if (event === 'SIGNED_OUT') {
    console.log('👋 User signed out');
    // Clear any cached data
    localStorage.removeItem('supabase.auth.token');
    localStorage.removeItem('sb-xeufezbuuccohiardtrk-auth-token');
  } else if (event === 'SIGNED_IN') {
    console.log('👋 User signed in');
  } else if (event === 'TOKEN_REFRESH_FAILED') {
    console.warn('⚠️ Token refresh failed, clearing auth data');
    // Clear invalid tokens
    localStorage.removeItem('supabase.auth.token');
    localStorage.removeItem('sb-xeufezbuuccohiardtrk-auth-token');
    // Optionally redirect to login
    if (window.location.pathname !== '/login' && window.location.pathname !== '/') {
      window.location.href = '/login';
    }
  }
});